[package]
name = "parser_file"
version = "0.2.1"
edition = "2021"
authors = ["michal.t.szymanski@gmail.com"]
description = "Parsing file"
license = "MIT OR Apache-2.0"
[dependencies]
exitcode = "1.1.2"
